import { Chapter } from "./types";

export const turbulenceModelsChapters: Chapter[] = [
  {
    id: "question",
    kicker: "01 — The Question",
    title: "Six turbulence models, one airfoil, two flow regimes",
    body: [
      "Every RANS simulation stands or falls with its turbulence model — and every CFD engineer eventually faces the same question: which one should I trust for this flow? This project, from the CFD application seminar (CFD-Anwendungsseminar) at the University of Stuttgart's Institute of Aerodynamics and Gas Dynamics (IAG), answers it the empirical way: run the same airfoil through six turbulence models and compare everything — pressure distributions, force coefficients, shock positions, convergence behaviour and computing time — against wind-tunnel truth.",
      "The test article is the RAE 2822, a classic transonic research airfoil with an extensive experimental database (AGARD-AR-138). Two of its documented wind-tunnel cases span the interesting range: Case 1, subsonic at Mach 0.676, Re = 5.7 million and α = 1.92°, and Case 9, transonic at Mach 0.73, Re = 6.5 million and α = 2.78° — the latter with a shock sitting on the upper surface, which is exactly where turbulence models start to disagree.",
      "The contenders cover the whole ladder of RANS closure complexity: two one-equation models (Spalart-Allmaras original and with Edwards modification), three two-equation models (k-ω, Menter Baseline and Menter SST), and a full Reynolds-stress model that solves a transport equation for every component of the stress tensor. All simulations ran in the DLR TAU code on meshes built in Pointwise, and beyond the two validation cases the models were pushed through full polar sweeps up to and past maximum lift — where the comparison got dramatic.",
    ],
    media: [
      {
        type: "image",
        src: "/images/turbulence-models/cover.png",
        alt: "Pressure coefficient field around the RAE 2822 airfoil with a shock on the upper surface",
        caption: "Where models disagree: instantaneous cp field around the RAE 2822 at high incidence, shock on the upper surface.",
        fit: "contain",
      },
    ],
    layout: "image-right",
    tags: ["RAE 2822", "DLR TAU", "University of Stuttgart · IAG"],
  },
  {
    id: "closure",
    kicker: "02 — The Closure Problem",
    title: "Why turbulence needs a model at all",
    body: [
      "Turbulence is unsteady, chaotic, three-dimensional and rotational — and above all a multi-scale problem: large eddies transport smaller ones down to the scales where viscosity dissipates them. Resolving all of that directly (DNS) needs grid counts growing roughly with Re^9/4, which puts an airfoil at flight Reynolds numbers hopelessly out of reach. The practical alternative is Reynolds averaging: split every flow quantity into mean and fluctuation, average the Navier-Stokes equations in time, and solve only for the mean flow.",
      "The averaging has a price. It produces an extra term — the Reynolds stress tensor, six independent unknowns describing the momentum exchange of the turbulent fluctuations — and no equation to determine them. The system is underdetermined; closing it is the entire job of a turbulence model, and the different ways of doing so define the model families in this comparison.",
      "Eddy-viscosity models take the cheap route via the Boussinesq hypothesis: assume the Reynolds stresses are proportional to the mean velocity gradient, analogous to Newton's law of viscosity, and model a single scalar eddy viscosity. Spalart-Allmaras does it with one transport equation; k-ω with two (turbulent kinetic energy and specific dissipation, strong near walls); Menter's Baseline model blends k-ω near the wall with k-ε in the free stream; and Menter SST adds a limiter on the eddy viscosity near the wall — the Bradshaw hypothesis — specifically to fix the prediction of separation under strong pressure gradients.",
      "Reynolds-stress models skip the Boussinesq shortcut entirely and solve a transport equation for each component of the stress tensor, capturing anisotropic turbulence, curved boundary layers and free vortices that eddy-viscosity models simplify away — in exchange for markedly higher computing cost and notoriously delicate numerics. The RSM used here builds on the Menter-BSL ω length-scale equation with isotropic dissipation.",
    ],
    layout: "text-only",
    tags: ["RANS", "Boussinesq Hypothesis", "Eddy Viscosity", "Reynolds Stress"],
  },
  {
    id: "mesh",
    kicker: "03 — The Mesh",
    title: "A hybrid mesh with a shock trap",
    body: [
      "The mesh is hybrid, built in three parts: a structured block hugging the airfoil to resolve the boundary layer, and two unstructured rings filling the space out to circles of one and eighty chord lengths. Surface point distributions are pinned by spacing constraints at the leading and trailing edges, and the first cell height is set via the y⁺ target — between 0.3 and 1.0 depending on resolution — so the boundary layer is genuinely resolved rather than bridged with wall functions.",
      "The transonic case got special treatment. A shock smeared over a coarse region contaminates every coefficient downstream of it, so its location was found first with a precursor run on the unrefined mesh — the intersection of the computed pressure distribution with the critical pressure coefficient marks where the flow goes supersonic and where it recovers — and the mesh was then refined there. The inner refinement circle was also squeezed into an ellipse (two chords long, one and a half high) to concentrate cells around the profile and its shock instead of wasting them above and below.",
    ],
    media: [
      {
        type: "image",
        src: "/images/turbulence-models/mesh-farfield.png",
        alt: "Hybrid mesh around the RAE 2822 with elliptic inner refinement region",
        caption: "The inner refinement region: structured boundary-layer block inside an elliptically deformed unstructured ring.",
        fit: "contain",
      },
      {
        type: "image",
        src: "/images/turbulence-models/mesh-leading-edge.png",
        alt: "Close-up of the structured boundary layer mesh at the leading edge",
        caption: "Leading edge close-up: the structured layers that resolve the boundary layer down to y⁺ < 1.",
        fit: "contain",
      },
    ],
    layout: "gallery",
    tags: ["Pointwise", "Hybrid Mesh", "y⁺ < 1", "Shock Refinement"],
  },
  {
    id: "convergence-study",
    kicker: "04 — Mesh Convergence",
    title: "Richardson extrapolation, and a first attempt that failed",
    body: [
      "Before comparing turbulence models, the discretisation error has to be pinned down — otherwise model differences and mesh artefacts blur together. The tool is Richardson extrapolation: run the same case on systematically refined meshes (total cell count doubling each step), fit the observed convergence order, and extrapolate to the value an infinitely fine mesh would produce. The distance of each mesh from that limit is its error estimate.",
      "The first attempt failed instructively. With the coarse, medium and fine meshes the fitted convergence order came out at p = 0.376 — far below the theoretical order of the scheme — because the fine mesh had already left the asymptotic range: its discretisation error was small enough that round-off and iteration error started to dominate, bending the curve the wrong way. More cells were actively hurting.",
      "The fix was to move the study window coarser instead of finer: a new intermediate mesh (scaling factor √1.5, dubbed 'mittelgrob') and a rebuilt coarse mesh with a matched refinement ratio. With that triplet the lift coefficient converged with p ≈ 3.2 and the drag coefficient with p ≈ 2.4, both cleanly asymptotic. The medium-coarse mesh — about 17,000 nodes, 0.58% lift error and 0.61% drag error against the extrapolated limit — was chosen for all following comparisons: accurate enough that model differences dominate, cheap enough to run six models through full polar sweeps.",
    ],
    media: [
      {
        type: "image",
        src: "/images/turbulence-models/richardson-failed.png",
        alt: "Failed Richardson extrapolation with convergence order 0.376",
        caption: "The failed attempt: p = 0.376 — the fine mesh has left the asymptotic range, so the extrapolation is meaningless.",
        fit: "contain",
      },
      {
        type: "image",
        src: "/images/turbulence-models/richardson-ca.png",
        alt: "Lift coefficient Richardson extrapolation with the new mesh set",
        caption: "The repaired study: with the new mesh triplet the lift coefficient converges at p ≈ 3.2; grey marks the non-asymptotic zones.",
        fit: "contain",
      },
      {
        type: "image",
        src: "/images/turbulence-models/richardson-cw.png",
        alt: "Drag coefficient Richardson extrapolation over mesh refinement",
        caption: "Same picture for drag: p ≈ 2.4, with the chosen 'mittelgrob' mesh 0.61% from the extrapolated value.",
        fit: "contain",
      },
    ],
    layout: "gallery",
    tags: ["Richardson Extrapolation", "Grid Convergence", "Error Estimation"],
  },
  {
    id: "subsonic",
    kicker: "05 — Subsonic Case",
    title: "Case 1: everyone agrees — almost",
    body: [
      "At Mach 0.676 and low incidence the flow stays attached and shock-free, and the models behave accordingly: all six pressure distributions lie practically on top of each other, matching the wind-tunnel curve through the suction peak and across the whole upper surface. Every model converged steadily to a density residual of 10⁻⁷ without drama. If this were the whole story, the cheapest model would win by default.",
      "The one systematic deviation isn't a model's fault. On the lower surface the measured pressure sits visibly below every simulation — consistent with wind-tunnel blockage: the model narrows the test-section cross-section, the flow accelerates around it, and the pressure drops per Bernoulli. The same offset shows up in the integral coefficients: all simulations cluster between lift coefficients of 0.577 and 0.598 while the tunnel reports 0.566, and the computed drag (95–100 counts) sits above the measured 85 counts for the same reason.",
      "The spread between the models themselves stays small — the two-equation k-ω is highest at 0.598, Menter SST lowest at 0.577 — a first hint of the pattern the transonic case would amplify.",
    ],
    media: [
      {
        type: "image",
        src: "/images/turbulence-models/cp-case1.png",
        alt: "Pressure coefficient distributions of SAE, k-omega, RSM and wind tunnel for the subsonic case",
        caption: "Subsonic pressure distributions: models indistinguishable, wind tunnel (black) slightly offset on the lower surface — blockage.",
        fit: "contain",
      },
      {
        type: "image",
        src: "/images/turbulence-models/convergence-case1.png",
        alt: "Density residual convergence of SAE, SST and RSM for the subsonic case",
        caption: "Subsonic convergence: all model families march down to 10⁻⁷ without complaint — even the RSM.",
        fit: "contain",
      },
    ],
    layout: "gallery",
    tags: ["Case 1", "Ma 0.676", "Tunnel Blockage"],
  },
  {
    id: "transonic",
    kicker: "06 — Transonic Case",
    title: "Case 9: the shock sorts the models",
    body: [
      "At Mach 0.73 a supersonic pocket forms on the upper surface and collapses through a shock at mid-chord — and now the models diverge exactly where the physics gets hard. The shock position was extracted objectively from each solution as the intersection of the pressure distribution with the critical pressure coefficient. The one-equation Spalart-Allmaras variants and the Reynolds-stress model all place the shock at x/c ≈ 0.56, in close agreement with the wind tunnel. The k-ω model puts it a full two percent chord too far downstream at 0.58 — its known habit of predicting separation and shock positions too far aft — and Menter Baseline, which is k-ω near the wall by construction, lands at the same spot.",
      "Menter SST shows precisely the behaviour it was designed for: its eddy-viscosity limiter pulls the shock back upstream to x/c ≈ 0.55 — overcorrecting slightly to the early side, but much closer than its k-ω base. The integral coefficients tell the same story: k-ω's late shock enlarges the suction area and inflates lift to 0.847 against the tunnel's 0.803, while SAO (0.800), SAE (0.801) and the RSM (0.814) land close, and SST sits slightly low at 0.788.",
      "The transonic case also cracked the first model's composure: the Reynolds-stress model's residual, smooth in the subsonic case, starts oscillating visibly on its way down — it still converges, but the reduced numerical robustness the literature promises is now on screen.",
    ],
    media: [
      {
        type: "image",
        src: "/images/turbulence-models/cp-case9.png",
        alt: "Transonic pressure distributions of SAE, k-omega, RSM and wind tunnel",
        caption: "Transonic pressure distributions: agreement everywhere except the one place that matters — the shock.",
        fit: "contain",
      },
      {
        type: "image",
        src: "/images/turbulence-models/cp-case9-shock.png",
        alt: "Close-up of the shock region showing k-omega placing the shock too far downstream",
        caption: "Shock close-up: k-ω (red) recovers a full 2% chord too late; SAE and RSM track the tunnel data (black).",
        fit: "contain",
      },
      {
        type: "image",
        src: "/images/turbulence-models/convergence-case9.png",
        alt: "Density residual convergence for the transonic case with oscillating RSM residual",
        caption: "Transonic convergence: the RSM residual (red) starts wobbling — the first sign of its fragile numerics.",
        fit: "contain",
      },
    ],
    layout: "gallery",
    tags: ["Case 9", "Ma 0.73", "Shock Position", "Critical cp"],
  },
  {
    id: "cost",
    kicker: "07 — The Bill",
    title: "What each closure level costs",
    body: [
      "Accuracy comparisons only mean something next to the price tag, so every run was timed under reproducible conditions on the same mesh. Within the eddy-viscosity family the differences are modest: the subsonic case takes 361 seconds with original Spalart-Allmaras and 411–472 seconds with the two-equation models; the transonic case scales everything up (596 seconds for SAO, 826–900 for the two-equation family) but keeps the ordering.",
      "The Reynolds-stress model is a different regime: 837 seconds subsonic and 1519 transonic — consistently around twice the cost of the two-equation models and up to 2.5 times the one-equation ones, driven by the extra transport equations and the more cautious convergence. That factor of two is the recurring theme of this comparison: the RSM was the most accurate model in almost every metric, and every one of those metrics was bought at double price.",
      "There is also a hidden cost item the stopwatch misses: Menter SST, unremarkable in the steady timings, forced the switch to time-accurate simulation much earlier than the other models as incidence increased — so its effective cost in the polar sweeps was far higher than its steady-state numbers suggest.",
    ],
    layout: "text-only",
    tags: ["Runtime", "RSM ≈ 2×", "Cost vs. Accuracy"],
  },
  {
    id: "polars",
    kicker: "08 — Polars to Stall",
    title: "Pushing past α = 6°, where steady CFD stops being steady",
    body: [
      "The wind-tunnel cases live below α = 3°, where every model behaves. The polar sweeps — flown with one representative per family: SAE, Menter SST and the RSM — push into the regime where the solution itself becomes the problem. Above roughly six degrees the steady computations stop converging and the force coefficients start ringing: the residual oscillates instead of dropping, and the 'converged' lift value depends on where you stop iterating.",
      "The remedy is honest time integration. In the unsteady runs two situations separate cleanly: at moderate incidence the lift coefficient still settles to a stable value, while at higher angles a genuine periodic oscillation develops that no amount of iteration will remove — the flow itself is unsteady. For those cases the coefficients entering the polar are time-averaged over the oscillation.",
      "The resulting polars around maximum lift disagree far more than any low-α result: SAE traces the textbook shape — a rounded lift peak of about 1.10 at six degrees with boundary-layer thickening, separation and stall discernible in the drag curve. The RSM carries the highest maximum lift, about 1.12. And Menter SST does something neither of the others does: after 6.5° its time-averaged lift collapses by nearly 0.2 within a quarter of a degree, with a matching kink in the otherwise linear drag curve. That cliff has a specific cause — the next chapter watches it happen.",
    ],
    media: [
      {
        type: "image",
        src: "/images/turbulence-models/stationary-oscillation.png",
        alt: "Oscillating lift coefficient in a steady computation at alpha 6 degrees",
        caption: "The symptom: at α = 6° the 'steady' solution rings instead of converging — time to integrate honestly.",
        fit: "contain",
      },
      {
        type: "image",
        src: "/images/turbulence-models/unsteady-cl.png",
        alt: "Unsteady lift coefficient histories at 6, 7 and 8 degrees angle of attack",
        caption: "Unsteady runs: α = 6° settles, α = 7° and 8° develop genuine periodic lift oscillations — these get time-averaged.",
        fit: "contain",
      },
      {
        type: "image",
        src: "/images/turbulence-models/polar-cl.png",
        alt: "Lift polars of SAE, SST and RSM around maximum lift",
        caption: "Lift around cl,max: RSM peaks highest, SAE rounds over classically — and SST (blue) falls off a cliff after 6.5°.",
        fit: "contain",
      },
      {
        type: "image",
        src: "/images/turbulence-models/polar-cw.png",
        alt: "Drag polars of SAE, SST and RSM at high angles of attack",
        caption: "The drag curves: near-linear growth for all models, with SST's kink at 6.5–6.75° mirroring its lift collapse.",
        fit: "contain",
      },
    ],
    layout: "gallery",
    tags: ["Polar Sweep", "Unsteady RANS", "Time-Averaging", "cl,max"],
  },
  {
    id: "buffet",
    kicker: "09 — Shock Buffet",
    title: "Anatomy of the SST lift collapse",
    body: [
      "Zooming into the two computations bracketing the cliff — α = 6.5° and 6.75° with Menter SST — reveals a shock buffet: the shock is no longer stationary but sweeps periodically across the upper surface, oscillating between roughly 4% and 56% chord. Each cycle the supersonic pocket builds, collapses, sheds and rebuilds; the animations of the Mach and pressure fields show the whole breathing motion.",
      "The surface pressure explains where the lift goes. At the low point of each cycle the upper- and lower-surface pressure distributions cross over the rear part of the airfoil — the aft loading reverses sign, the rear of the airfoil briefly lifts downward, and the instantaneous lift dips far below its shock-quiet value. The lift coefficient still touches its former level once per period, but the time average — which is what the polar records — collapses. At 6.5° the curves never cross and the polar stays intact; a quarter degree later they do.",
      "This is exactly the flow situation the summary tables warn about with 'convergence problems in separated flow' — experienced live: SST's limited eddy viscosity, the very mechanism that fixed the shock position in Case 9, also makes it the first model to let the shock start moving.",
    ],
    media: [
      {
        type: "video",
        src: "/videos/turbulence-models/buffet-mach.mp4",
        alt: "Animation of the Mach number field during shock buffet at alpha 6.75 degrees",
        caption: "Shock buffet at α = 6.75° (SST): the supersonic pocket builds and collapses, the shock sweeping between 4% and 56% chord.",
      },
      {
        type: "video",
        src: "/videos/turbulence-models/buffet-cp-field.mp4",
        alt: "Animation of the pressure coefficient field during shock buffet",
        caption: "The same cycle in the cp field — watch the suction plateau detach and re-form.",
      },
      {
        type: "video",
        src: "/videos/turbulence-models/buffet-cp-surface.mp4",
        alt: "Animation of the surface pressure distribution during a buffet cycle",
        caption: "Surface pressure through one period: at the low point the upper and lower curves cross aft — the rear loading reverses.",
      },
      {
        type: "image",
        src: "/images/turbulence-models/buffet-cp-crossing.png",
        alt: "Upper and lower surface pressure distributions at the lift minimum of the buffet cycle",
        caption: "Frozen at the lift minimum: upper (blue) and lower (red) surface pressures meet near the trailing edge.",
        fit: "contain",
      },
    ],
    layout: "gallery",
    tags: ["Shock Buffet", "Menter SST", "Unsteady Aerodynamics"],
  },
  {
    id: "alpha7",
    kicker: "10 — Three Models, One Buffet",
    title: "α = 7°: same flow, three different movies",
    body: [
      "At seven degrees all three models agree the flow is unsteady — and disagree on almost everything else about it. Side by side, the pressure-field animations show three different renditions of the same buffet: the Spalart-Allmaras model oscillates with a period of 73 ms, Menter SST slowest at 78 ms with the largest excursions and the most chaotic field, and the Reynolds-stress model fastest at 64 ms.",
      "This is the sobering endnote of the comparison: in exactly the regime where a designer would most want a trustworthy answer — buffet onset, the boundary of the safe flight envelope — the models diverge not by percent but qualitatively, in amplitude, frequency and character of the unsteadiness. Below buffet onset any of them would do; at it, the model choice is the answer.",
    ],
    media: [
      {
        type: "video",
        src: "/videos/turbulence-models/alpha7-sao.mp4",
        alt: "Pressure field animation at alpha 7 degrees computed with Spalart-Allmaras",
        caption: "Spalart-Allmaras original: buffet period 73.1 ms.",
      },
      {
        type: "video",
        src: "/videos/turbulence-models/alpha7-sst.mp4",
        alt: "Pressure field animation at alpha 7 degrees computed with Menter SST",
        caption: "Menter SST: the slowest and wildest of the three — period 77.8 ms.",
      },
      {
        type: "video",
        src: "/videos/turbulence-models/alpha7-rsm.mp4",
        alt: "Pressure field animation at alpha 7 degrees computed with the Reynolds stress model",
        caption: "Reynolds-stress model: fastest cycle at 63.7 ms.",
      },
    ],
    layout: "gallery",
    tags: ["Buffet Onset", "Model Divergence", "α = 7°"],
  },
  {
    id: "verdict",
    kicker: "11 — The Verdict",
    title: "Which model, when — with the receipts",
    body: [
      "The simulations confirmed most of the textbook character sheet, and corrected part of it. Spalart-Allmaras delivered its promised robustness and the shortest runtimes, and — against its reputation — did not place separation noticeably too far downstream in these cases. k-ω and Menter Baseline were equally robust and, as advertised, strong near the wall, but both parked the transonic shock too far aft; since BSL is k-ω near the wall and these cases are wall-dominated, the two were near-twins throughout. Menter SST demonstrably corrects the shock and separation position via its eddy-viscosity limiter — and paid for it by going unsteady earliest, with chaotic fields in separated flow. The Reynolds-stress model was the closest to the wind tunnel in most metrics, and cost twice as much time along with the shakiest numerics.",
      "The practical recommendation that falls out: for wall-bounded aerodynamic flows of this kind, k-ω is a strong default — a good compromise of runtime, stability and solution quality. Where the flow is complex and the budget allows, the RSM is worth its price. For simple, largely attached flows, Spalart-Allmaras gives solid answers fastest. And any result near buffet onset should be treated as model-dependent until proven otherwise.",
      "Two methodological lessons ride along: a mesh convergence study can fail in the non-obvious direction (chapter 04's too-fine mesh), and the prescribed transition location at 4% chord — versus the experiment's 11% subsonic and 3% transonic — is exactly the kind of quiet inconsistency to hunt down before blaming the turbulence model for a mismatch.",
    ],
    layout: "text-only",
    tags: ["Recommendations", "k-ω as Default", "Lessons Learned"],
  },
];
